server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diary
    username: root
    password: Stxx@1234
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
